- repo: https://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    - id: validate-toml
    - id: no-go-testing
    - id: go-mod-tidy

