// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

/* Specify the name of the generated file's package. */ package copygen

import (
	"github.com/TcMits/ent-clean-template/ent"
	useCaseModel "github.com/TcMits/ent-clean-template/pkg/entity/model/usecase"
)

// LoginInputToUserWhereInput copies a *useCaseModel.LoginInput to a *ent.UserWhereInput.
func LoginInputToUserWhereInput(tU *ent.UserWhereInput, fL *useCaseModel.LoginInput) {
	// *ent.UserWhereInput fields
	tU.Username = &fL.Username
}

// PublicMeUseCaseUpdateInputToUserUpdateInput copies a *useCaseModel.PublicMeUseCaseUpdateInput to a *ent.UserUpdateInput.
func PublicMeUseCaseUpdateInputToUserUpdateInput(tU *ent.UserUpdateInput, fP *useCaseModel.PublicMeUseCaseUpdateInput) {
	// *ent.UserUpdateInput fields
	tU.Username = fP.Username
	tU.FirstName = fP.FirstName
	tU.LastName = fP.LastName
	tU.Email = fP.Email
}
