// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserColumns holds the columns for the "User" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "jwt_token_key", Type: field.TypeString},
		{Name: "password", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"mysql": "char(32)"}},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "first_name", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "last_name", Type: field.TypeString, Size: 128, Default: ""},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "is_staff", Type: field.TypeBool},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "join_time", Type: field.TypeTime},
	}
	// UserTable holds the schema information for the "User" table.
	UserTable = &schema.Table{
		Name:       "User",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserTable,
	}
)

func init() {
	UserTable.Annotation = &entsql.Annotation{
		Table: "User",
	}
}
