// Code generated by ent, DO NOT EDIT.

package ent

import (
	"errors"
	"fmt"
	"time"

	"github.com/TcMits/ent-clean-template/ent/predicate"
	"github.com/TcMits/ent-clean-template/ent/user"
	"github.com/google/uuid"
)

// UserWhereInput represents a where input for filtering User queries.
type UserWhereInput struct {
	Predicates []predicate.User  `json:"-"`
	Not        *UserWhereInput   `json:"not,omitempty"`
	Or         []*UserWhereInput `json:"or,omitempty"`
	And        []*UserWhereInput `json:"and,omitempty"`

	// "id" field predicates.
	ID      *uuid.UUID  `json:"id,omitempty" form:"id" param:"id" url:"id"`
	IDNEQ   *uuid.UUID  `json:"id_neq,omitempty" form:"id_neq" param:"id_neq" url:"id_neq"`
	IDIn    []uuid.UUID `json:"id_in,omitempty" form:"id_in" param:"id_in" url:"id_in"`
	IDNotIn []uuid.UUID `json:"id_not_in,omitempty" form:"id_not_in" param:"id_not_in" url:"id_not_in"`
	IDGT    *uuid.UUID  `json:"id_gt,omitempty" form:"id_gt" param:"id_gt" url:"id_gt"`
	IDGTE   *uuid.UUID  `json:"id_gte,omitempty" form:"id_gte" param:"id_gte" url:"id_gte"`
	IDLT    *uuid.UUID  `json:"id_lt,omitempty" form:"id_lt" param:"id_lt" url:"id_lt"`
	IDLTE   *uuid.UUID  `json:"id_lte,omitempty" form:"id_lte" param:"id_lte" url:"id_lte"`

	// "create_time" field predicates.
	CreateTime      *time.Time  `json:"create_time,omitempty" form:"create_time" param:"create_time" url:"create_time"`
	CreateTimeNEQ   *time.Time  `json:"create_time_neq,omitempty" form:"create_time_neq" param:"create_time_neq" url:"create_time_neq"`
	CreateTimeIn    []time.Time `json:"create_time_in,omitempty" form:"create_time_in" param:"create_time_in" url:"create_time_in"`
	CreateTimeNotIn []time.Time `json:"create_time_not_in,omitempty" form:"create_time_not_in" param:"create_time_not_in" url:"create_time_not_in"`
	CreateTimeGT    *time.Time  `json:"create_time_gt,omitempty" form:"create_time_gt" param:"create_time_gt" url:"create_time_gt"`
	CreateTimeGTE   *time.Time  `json:"create_time_gte,omitempty" form:"create_time_gte" param:"create_time_gte" url:"create_time_gte"`
	CreateTimeLT    *time.Time  `json:"create_time_lt,omitempty" form:"create_time_lt" param:"create_time_lt" url:"create_time_lt"`
	CreateTimeLTE   *time.Time  `json:"create_time_lte,omitempty" form:"create_time_lte" param:"create_time_lte" url:"create_time_lte"`

	// "update_time" field predicates.
	UpdateTime      *time.Time  `json:"update_time,omitempty" form:"update_time" param:"update_time" url:"update_time"`
	UpdateTimeNEQ   *time.Time  `json:"update_time_neq,omitempty" form:"update_time_neq" param:"update_time_neq" url:"update_time_neq"`
	UpdateTimeIn    []time.Time `json:"update_time_in,omitempty" form:"update_time_in" param:"update_time_in" url:"update_time_in"`
	UpdateTimeNotIn []time.Time `json:"update_time_not_in,omitempty" form:"update_time_not_in" param:"update_time_not_in" url:"update_time_not_in"`
	UpdateTimeGT    *time.Time  `json:"update_time_gt,omitempty" form:"update_time_gt" param:"update_time_gt" url:"update_time_gt"`
	UpdateTimeGTE   *time.Time  `json:"update_time_gte,omitempty" form:"update_time_gte" param:"update_time_gte" url:"update_time_gte"`
	UpdateTimeLT    *time.Time  `json:"update_time_lt,omitempty" form:"update_time_lt" param:"update_time_lt" url:"update_time_lt"`
	UpdateTimeLTE   *time.Time  `json:"update_time_lte,omitempty" form:"update_time_lte" param:"update_time_lte" url:"update_time_lte"`

	// "username" field predicates.
	Username             *string  `json:"username,omitempty" form:"username" param:"username" url:"username"`
	UsernameNEQ          *string  `json:"username_neq,omitempty" form:"username_neq" param:"username_neq" url:"username_neq"`
	UsernameIn           []string `json:"username_in,omitempty" form:"username_in" param:"username_in" url:"username_in"`
	UsernameNotIn        []string `json:"username_not_in,omitempty" form:"username_not_in" param:"username_not_in" url:"username_not_in"`
	UsernameGT           *string  `json:"username_gt,omitempty" form:"username_gt" param:"username_gt" url:"username_gt"`
	UsernameGTE          *string  `json:"username_gte,omitempty" form:"username_gte" param:"username_gte" url:"username_gte"`
	UsernameLT           *string  `json:"username_lt,omitempty" form:"username_lt" param:"username_lt" url:"username_lt"`
	UsernameLTE          *string  `json:"username_lte,omitempty" form:"username_lte" param:"username_lte" url:"username_lte"`
	UsernameContains     *string  `json:"username_contains,omitempty" form:"username_contains" param:"username_contains" url:"username_contains"`
	UsernameHasPrefix    *string  `json:"username_has_prefix,omitempty" form:"username_has_prefix" param:"username_has_prefix" url:"username_has_prefix"`
	UsernameHasSuffix    *string  `json:"username_has_suffix,omitempty" form:"username_has_suffix" param:"username_has_suffix" url:"username_has_suffix"`
	UsernameEqualFold    *string  `json:"username_equal_fold,omitempty" form:"username_equal_fold" param:"username_equal_fold" url:"username_equal_fold"`
	UsernameContainsFold *string  `json:"username_contains_fold,omitempty" form:"username_contains_fold" param:"username_contains_fold" url:"username_contains_fold"`

	// "first_name" field predicates.
	FirstName             *string  `json:"first_name,omitempty" form:"first_name" param:"first_name" url:"first_name"`
	FirstNameNEQ          *string  `json:"first_name_neq,omitempty" form:"first_name_neq" param:"first_name_neq" url:"first_name_neq"`
	FirstNameIn           []string `json:"first_name_in,omitempty" form:"first_name_in" param:"first_name_in" url:"first_name_in"`
	FirstNameNotIn        []string `json:"first_name_not_in,omitempty" form:"first_name_not_in" param:"first_name_not_in" url:"first_name_not_in"`
	FirstNameGT           *string  `json:"first_name_gt,omitempty" form:"first_name_gt" param:"first_name_gt" url:"first_name_gt"`
	FirstNameGTE          *string  `json:"first_name_gte,omitempty" form:"first_name_gte" param:"first_name_gte" url:"first_name_gte"`
	FirstNameLT           *string  `json:"first_name_lt,omitempty" form:"first_name_lt" param:"first_name_lt" url:"first_name_lt"`
	FirstNameLTE          *string  `json:"first_name_lte,omitempty" form:"first_name_lte" param:"first_name_lte" url:"first_name_lte"`
	FirstNameContains     *string  `json:"first_name_contains,omitempty" form:"first_name_contains" param:"first_name_contains" url:"first_name_contains"`
	FirstNameHasPrefix    *string  `json:"first_name_has_prefix,omitempty" form:"first_name_has_prefix" param:"first_name_has_prefix" url:"first_name_has_prefix"`
	FirstNameHasSuffix    *string  `json:"first_name_has_suffix,omitempty" form:"first_name_has_suffix" param:"first_name_has_suffix" url:"first_name_has_suffix"`
	FirstNameIsNil        bool     `json:"first_name_is_nil,omitempty" form:"first_name_is_nil" param:"first_name_is_nil" url:"first_name_is_nil"`
	FirstNameNotNil       bool     `json:"first_name_not_nil,omitempty" form:"first_name_not_nil" param:"first_name_not_nil" url:"first_name_not_nil"`
	FirstNameEqualFold    *string  `json:"first_name_equal_fold,omitempty" form:"first_name_equal_fold" param:"first_name_equal_fold" url:"first_name_equal_fold"`
	FirstNameContainsFold *string  `json:"first_name_contains_fold,omitempty" form:"first_name_contains_fold" param:"first_name_contains_fold" url:"first_name_contains_fold"`

	// "last_name" field predicates.
	LastName             *string  `json:"last_name,omitempty" form:"last_name" param:"last_name" url:"last_name"`
	LastNameNEQ          *string  `json:"last_name_neq,omitempty" form:"last_name_neq" param:"last_name_neq" url:"last_name_neq"`
	LastNameIn           []string `json:"last_name_in,omitempty" form:"last_name_in" param:"last_name_in" url:"last_name_in"`
	LastNameNotIn        []string `json:"last_name_not_in,omitempty" form:"last_name_not_in" param:"last_name_not_in" url:"last_name_not_in"`
	LastNameGT           *string  `json:"last_name_gt,omitempty" form:"last_name_gt" param:"last_name_gt" url:"last_name_gt"`
	LastNameGTE          *string  `json:"last_name_gte,omitempty" form:"last_name_gte" param:"last_name_gte" url:"last_name_gte"`
	LastNameLT           *string  `json:"last_name_lt,omitempty" form:"last_name_lt" param:"last_name_lt" url:"last_name_lt"`
	LastNameLTE          *string  `json:"last_name_lte,omitempty" form:"last_name_lte" param:"last_name_lte" url:"last_name_lte"`
	LastNameContains     *string  `json:"last_name_contains,omitempty" form:"last_name_contains" param:"last_name_contains" url:"last_name_contains"`
	LastNameHasPrefix    *string  `json:"last_name_has_prefix,omitempty" form:"last_name_has_prefix" param:"last_name_has_prefix" url:"last_name_has_prefix"`
	LastNameHasSuffix    *string  `json:"last_name_has_suffix,omitempty" form:"last_name_has_suffix" param:"last_name_has_suffix" url:"last_name_has_suffix"`
	LastNameIsNil        bool     `json:"last_name_is_nil,omitempty" form:"last_name_is_nil" param:"last_name_is_nil" url:"last_name_is_nil"`
	LastNameNotNil       bool     `json:"last_name_not_nil,omitempty" form:"last_name_not_nil" param:"last_name_not_nil" url:"last_name_not_nil"`
	LastNameEqualFold    *string  `json:"last_name_equal_fold,omitempty" form:"last_name_equal_fold" param:"last_name_equal_fold" url:"last_name_equal_fold"`
	LastNameContainsFold *string  `json:"last_name_contains_fold,omitempty" form:"last_name_contains_fold" param:"last_name_contains_fold" url:"last_name_contains_fold"`

	// "email" field predicates.
	Email             *string  `json:"email,omitempty" form:"email" param:"email" url:"email"`
	EmailNEQ          *string  `json:"email_neq,omitempty" form:"email_neq" param:"email_neq" url:"email_neq"`
	EmailIn           []string `json:"email_in,omitempty" form:"email_in" param:"email_in" url:"email_in"`
	EmailNotIn        []string `json:"email_not_in,omitempty" form:"email_not_in" param:"email_not_in" url:"email_not_in"`
	EmailGT           *string  `json:"email_gt,omitempty" form:"email_gt" param:"email_gt" url:"email_gt"`
	EmailGTE          *string  `json:"email_gte,omitempty" form:"email_gte" param:"email_gte" url:"email_gte"`
	EmailLT           *string  `json:"email_lt,omitempty" form:"email_lt" param:"email_lt" url:"email_lt"`
	EmailLTE          *string  `json:"email_lte,omitempty" form:"email_lte" param:"email_lte" url:"email_lte"`
	EmailContains     *string  `json:"email_contains,omitempty" form:"email_contains" param:"email_contains" url:"email_contains"`
	EmailHasPrefix    *string  `json:"email_has_prefix,omitempty" form:"email_has_prefix" param:"email_has_prefix" url:"email_has_prefix"`
	EmailHasSuffix    *string  `json:"email_has_suffix,omitempty" form:"email_has_suffix" param:"email_has_suffix" url:"email_has_suffix"`
	EmailEqualFold    *string  `json:"email_equal_fold,omitempty" form:"email_equal_fold" param:"email_equal_fold" url:"email_equal_fold"`
	EmailContainsFold *string  `json:"email_contains_fold,omitempty" form:"email_contains_fold" param:"email_contains_fold" url:"email_contains_fold"`

	// "is_staff" field predicates.
	IsStaff       *bool `json:"is_staff,omitempty" form:"is_staff" param:"is_staff" url:"is_staff"`
	IsStaffNEQ    *bool `json:"is_staff_neq,omitempty" form:"is_staff_neq" param:"is_staff_neq" url:"is_staff_neq"`
	IsStaffIsNil  bool  `json:"is_staff_is_nil,omitempty" form:"is_staff_is_nil" param:"is_staff_is_nil" url:"is_staff_is_nil"`
	IsStaffNotNil bool  `json:"is_staff_not_nil,omitempty" form:"is_staff_not_nil" param:"is_staff_not_nil" url:"is_staff_not_nil"`

	// "is_superuser" field predicates.
	IsSuperuser       *bool `json:"is_superuser,omitempty" form:"is_superuser" param:"is_superuser" url:"is_superuser"`
	IsSuperuserNEQ    *bool `json:"is_superuser_neq,omitempty" form:"is_superuser_neq" param:"is_superuser_neq" url:"is_superuser_neq"`
	IsSuperuserIsNil  bool  `json:"is_superuser_is_nil,omitempty" form:"is_superuser_is_nil" param:"is_superuser_is_nil" url:"is_superuser_is_nil"`
	IsSuperuserNotNil bool  `json:"is_superuser_not_nil,omitempty" form:"is_superuser_not_nil" param:"is_superuser_not_nil" url:"is_superuser_not_nil"`

	// "is_active" field predicates.
	IsActive       *bool `json:"is_active,omitempty" form:"is_active" param:"is_active" url:"is_active"`
	IsActiveNEQ    *bool `json:"is_active_neq,omitempty" form:"is_active_neq" param:"is_active_neq" url:"is_active_neq"`
	IsActiveIsNil  bool  `json:"is_active_is_nil,omitempty" form:"is_active_is_nil" param:"is_active_is_nil" url:"is_active_is_nil"`
	IsActiveNotNil bool  `json:"is_active_not_nil,omitempty" form:"is_active_not_nil" param:"is_active_not_nil" url:"is_active_not_nil"`
}

// AddPredicates adds custom predicates to the where input to be used during the filtering phase.
func (i *UserWhereInput) AddPredicates(predicates ...predicate.User) {
	i.Predicates = append(i.Predicates, predicates...)
}

// Filter applies the UserWhereInput filter on the UserQuery builder.
func (i *UserWhereInput) Filter(q *UserQuery) (*UserQuery, error) {
	if i == nil {
		return q, nil
	}
	p, err := i.P()
	if err != nil {
		if err == ErrEmptyUserWhereInput {
			return q, nil
		}
		return nil, err
	}
	return q.Where(p), nil
}

// ErrEmptyUserWhereInput is returned in case the UserWhereInput is empty.
var ErrEmptyUserWhereInput = errors.New("ent: empty predicate UserWhereInput")

// P returns a predicate for filtering users.
// An error is returned if the input is empty or invalid.
func (i *UserWhereInput) P() (predicate.User, error) {
	var predicates []predicate.User
	if i.Not != nil {
		p, err := i.Not.P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'not'", err)
		}
		predicates = append(predicates, user.Not(p))
	}
	switch n := len(i.Or); {
	case n == 1:
		p, err := i.Or[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'or'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		or := make([]predicate.User, 0, n)
		for _, w := range i.Or {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'or'", err)
			}
			or = append(or, p)
		}
		predicates = append(predicates, user.Or(or...))
	}
	switch n := len(i.And); {
	case n == 1:
		p, err := i.And[0].P()
		if err != nil {
			return nil, fmt.Errorf("%w: field 'and'", err)
		}
		predicates = append(predicates, p)
	case n > 1:
		and := make([]predicate.User, 0, n)
		for _, w := range i.And {
			p, err := w.P()
			if err != nil {
				return nil, fmt.Errorf("%w: field 'and'", err)
			}
			and = append(and, p)
		}
		predicates = append(predicates, user.And(and...))
	}
	predicates = append(predicates, i.Predicates...)
	if i.ID != nil {
		predicates = append(predicates, user.IDEQ(*i.ID))
	}
	if i.IDNEQ != nil {
		predicates = append(predicates, user.IDNEQ(*i.IDNEQ))
	}
	if len(i.IDIn) > 0 {
		predicates = append(predicates, user.IDIn(i.IDIn...))
	}
	if len(i.IDNotIn) > 0 {
		predicates = append(predicates, user.IDNotIn(i.IDNotIn...))
	}
	if i.IDGT != nil {
		predicates = append(predicates, user.IDGT(*i.IDGT))
	}
	if i.IDGTE != nil {
		predicates = append(predicates, user.IDGTE(*i.IDGTE))
	}
	if i.IDLT != nil {
		predicates = append(predicates, user.IDLT(*i.IDLT))
	}
	if i.IDLTE != nil {
		predicates = append(predicates, user.IDLTE(*i.IDLTE))
	}
	if i.CreateTime != nil {
		predicates = append(predicates, user.CreateTimeEQ(*i.CreateTime))
	}
	if i.CreateTimeNEQ != nil {
		predicates = append(predicates, user.CreateTimeNEQ(*i.CreateTimeNEQ))
	}
	if len(i.CreateTimeIn) > 0 {
		predicates = append(predicates, user.CreateTimeIn(i.CreateTimeIn...))
	}
	if len(i.CreateTimeNotIn) > 0 {
		predicates = append(predicates, user.CreateTimeNotIn(i.CreateTimeNotIn...))
	}
	if i.CreateTimeGT != nil {
		predicates = append(predicates, user.CreateTimeGT(*i.CreateTimeGT))
	}
	if i.CreateTimeGTE != nil {
		predicates = append(predicates, user.CreateTimeGTE(*i.CreateTimeGTE))
	}
	if i.CreateTimeLT != nil {
		predicates = append(predicates, user.CreateTimeLT(*i.CreateTimeLT))
	}
	if i.CreateTimeLTE != nil {
		predicates = append(predicates, user.CreateTimeLTE(*i.CreateTimeLTE))
	}
	if i.UpdateTime != nil {
		predicates = append(predicates, user.UpdateTimeEQ(*i.UpdateTime))
	}
	if i.UpdateTimeNEQ != nil {
		predicates = append(predicates, user.UpdateTimeNEQ(*i.UpdateTimeNEQ))
	}
	if len(i.UpdateTimeIn) > 0 {
		predicates = append(predicates, user.UpdateTimeIn(i.UpdateTimeIn...))
	}
	if len(i.UpdateTimeNotIn) > 0 {
		predicates = append(predicates, user.UpdateTimeNotIn(i.UpdateTimeNotIn...))
	}
	if i.UpdateTimeGT != nil {
		predicates = append(predicates, user.UpdateTimeGT(*i.UpdateTimeGT))
	}
	if i.UpdateTimeGTE != nil {
		predicates = append(predicates, user.UpdateTimeGTE(*i.UpdateTimeGTE))
	}
	if i.UpdateTimeLT != nil {
		predicates = append(predicates, user.UpdateTimeLT(*i.UpdateTimeLT))
	}
	if i.UpdateTimeLTE != nil {
		predicates = append(predicates, user.UpdateTimeLTE(*i.UpdateTimeLTE))
	}
	if i.Username != nil {
		predicates = append(predicates, user.UsernameEQ(*i.Username))
	}
	if i.UsernameNEQ != nil {
		predicates = append(predicates, user.UsernameNEQ(*i.UsernameNEQ))
	}
	if len(i.UsernameIn) > 0 {
		predicates = append(predicates, user.UsernameIn(i.UsernameIn...))
	}
	if len(i.UsernameNotIn) > 0 {
		predicates = append(predicates, user.UsernameNotIn(i.UsernameNotIn...))
	}
	if i.UsernameGT != nil {
		predicates = append(predicates, user.UsernameGT(*i.UsernameGT))
	}
	if i.UsernameGTE != nil {
		predicates = append(predicates, user.UsernameGTE(*i.UsernameGTE))
	}
	if i.UsernameLT != nil {
		predicates = append(predicates, user.UsernameLT(*i.UsernameLT))
	}
	if i.UsernameLTE != nil {
		predicates = append(predicates, user.UsernameLTE(*i.UsernameLTE))
	}
	if i.UsernameContains != nil {
		predicates = append(predicates, user.UsernameContains(*i.UsernameContains))
	}
	if i.UsernameHasPrefix != nil {
		predicates = append(predicates, user.UsernameHasPrefix(*i.UsernameHasPrefix))
	}
	if i.UsernameHasSuffix != nil {
		predicates = append(predicates, user.UsernameHasSuffix(*i.UsernameHasSuffix))
	}
	if i.UsernameEqualFold != nil {
		predicates = append(predicates, user.UsernameEqualFold(*i.UsernameEqualFold))
	}
	if i.UsernameContainsFold != nil {
		predicates = append(predicates, user.UsernameContainsFold(*i.UsernameContainsFold))
	}
	if i.FirstName != nil {
		predicates = append(predicates, user.FirstNameEQ(*i.FirstName))
	}
	if i.FirstNameNEQ != nil {
		predicates = append(predicates, user.FirstNameNEQ(*i.FirstNameNEQ))
	}
	if len(i.FirstNameIn) > 0 {
		predicates = append(predicates, user.FirstNameIn(i.FirstNameIn...))
	}
	if len(i.FirstNameNotIn) > 0 {
		predicates = append(predicates, user.FirstNameNotIn(i.FirstNameNotIn...))
	}
	if i.FirstNameGT != nil {
		predicates = append(predicates, user.FirstNameGT(*i.FirstNameGT))
	}
	if i.FirstNameGTE != nil {
		predicates = append(predicates, user.FirstNameGTE(*i.FirstNameGTE))
	}
	if i.FirstNameLT != nil {
		predicates = append(predicates, user.FirstNameLT(*i.FirstNameLT))
	}
	if i.FirstNameLTE != nil {
		predicates = append(predicates, user.FirstNameLTE(*i.FirstNameLTE))
	}
	if i.FirstNameContains != nil {
		predicates = append(predicates, user.FirstNameContains(*i.FirstNameContains))
	}
	if i.FirstNameHasPrefix != nil {
		predicates = append(predicates, user.FirstNameHasPrefix(*i.FirstNameHasPrefix))
	}
	if i.FirstNameHasSuffix != nil {
		predicates = append(predicates, user.FirstNameHasSuffix(*i.FirstNameHasSuffix))
	}
	if i.FirstNameIsNil {
		predicates = append(predicates, user.FirstNameIsNil())
	}
	if i.FirstNameNotNil {
		predicates = append(predicates, user.FirstNameNotNil())
	}
	if i.FirstNameEqualFold != nil {
		predicates = append(predicates, user.FirstNameEqualFold(*i.FirstNameEqualFold))
	}
	if i.FirstNameContainsFold != nil {
		predicates = append(predicates, user.FirstNameContainsFold(*i.FirstNameContainsFold))
	}
	if i.LastName != nil {
		predicates = append(predicates, user.LastNameEQ(*i.LastName))
	}
	if i.LastNameNEQ != nil {
		predicates = append(predicates, user.LastNameNEQ(*i.LastNameNEQ))
	}
	if len(i.LastNameIn) > 0 {
		predicates = append(predicates, user.LastNameIn(i.LastNameIn...))
	}
	if len(i.LastNameNotIn) > 0 {
		predicates = append(predicates, user.LastNameNotIn(i.LastNameNotIn...))
	}
	if i.LastNameGT != nil {
		predicates = append(predicates, user.LastNameGT(*i.LastNameGT))
	}
	if i.LastNameGTE != nil {
		predicates = append(predicates, user.LastNameGTE(*i.LastNameGTE))
	}
	if i.LastNameLT != nil {
		predicates = append(predicates, user.LastNameLT(*i.LastNameLT))
	}
	if i.LastNameLTE != nil {
		predicates = append(predicates, user.LastNameLTE(*i.LastNameLTE))
	}
	if i.LastNameContains != nil {
		predicates = append(predicates, user.LastNameContains(*i.LastNameContains))
	}
	if i.LastNameHasPrefix != nil {
		predicates = append(predicates, user.LastNameHasPrefix(*i.LastNameHasPrefix))
	}
	if i.LastNameHasSuffix != nil {
		predicates = append(predicates, user.LastNameHasSuffix(*i.LastNameHasSuffix))
	}
	if i.LastNameIsNil {
		predicates = append(predicates, user.LastNameIsNil())
	}
	if i.LastNameNotNil {
		predicates = append(predicates, user.LastNameNotNil())
	}
	if i.LastNameEqualFold != nil {
		predicates = append(predicates, user.LastNameEqualFold(*i.LastNameEqualFold))
	}
	if i.LastNameContainsFold != nil {
		predicates = append(predicates, user.LastNameContainsFold(*i.LastNameContainsFold))
	}
	if i.Email != nil {
		predicates = append(predicates, user.EmailEQ(*i.Email))
	}
	if i.EmailNEQ != nil {
		predicates = append(predicates, user.EmailNEQ(*i.EmailNEQ))
	}
	if len(i.EmailIn) > 0 {
		predicates = append(predicates, user.EmailIn(i.EmailIn...))
	}
	if len(i.EmailNotIn) > 0 {
		predicates = append(predicates, user.EmailNotIn(i.EmailNotIn...))
	}
	if i.EmailGT != nil {
		predicates = append(predicates, user.EmailGT(*i.EmailGT))
	}
	if i.EmailGTE != nil {
		predicates = append(predicates, user.EmailGTE(*i.EmailGTE))
	}
	if i.EmailLT != nil {
		predicates = append(predicates, user.EmailLT(*i.EmailLT))
	}
	if i.EmailLTE != nil {
		predicates = append(predicates, user.EmailLTE(*i.EmailLTE))
	}
	if i.EmailContains != nil {
		predicates = append(predicates, user.EmailContains(*i.EmailContains))
	}
	if i.EmailHasPrefix != nil {
		predicates = append(predicates, user.EmailHasPrefix(*i.EmailHasPrefix))
	}
	if i.EmailHasSuffix != nil {
		predicates = append(predicates, user.EmailHasSuffix(*i.EmailHasSuffix))
	}
	if i.EmailEqualFold != nil {
		predicates = append(predicates, user.EmailEqualFold(*i.EmailEqualFold))
	}
	if i.EmailContainsFold != nil {
		predicates = append(predicates, user.EmailContainsFold(*i.EmailContainsFold))
	}
	if i.IsStaff != nil {
		predicates = append(predicates, user.IsStaffEQ(*i.IsStaff))
	}
	if i.IsStaffNEQ != nil {
		predicates = append(predicates, user.IsStaffNEQ(*i.IsStaffNEQ))
	}
	if i.IsStaffIsNil {
		predicates = append(predicates, user.IsStaffIsNil())
	}
	if i.IsStaffNotNil {
		predicates = append(predicates, user.IsStaffNotNil())
	}
	if i.IsSuperuser != nil {
		predicates = append(predicates, user.IsSuperuserEQ(*i.IsSuperuser))
	}
	if i.IsSuperuserNEQ != nil {
		predicates = append(predicates, user.IsSuperuserNEQ(*i.IsSuperuserNEQ))
	}
	if i.IsSuperuserIsNil {
		predicates = append(predicates, user.IsSuperuserIsNil())
	}
	if i.IsSuperuserNotNil {
		predicates = append(predicates, user.IsSuperuserNotNil())
	}
	if i.IsActive != nil {
		predicates = append(predicates, user.IsActiveEQ(*i.IsActive))
	}
	if i.IsActiveNEQ != nil {
		predicates = append(predicates, user.IsActiveNEQ(*i.IsActiveNEQ))
	}
	if i.IsActiveIsNil {
		predicates = append(predicates, user.IsActiveIsNil())
	}
	if i.IsActiveNotNil {
		predicates = append(predicates, user.IsActiveNotNil())
	}

	switch len(predicates) {
	case 0:
		return nil, ErrEmptyUserWhereInput
	case 1:
		return predicates[0], nil
	default:
		return user.And(predicates...), nil
	}
}
