// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

type FilterFunc func(*sql.Selector)

// User is the predicate function for user builders.
type User = FilterFunc
